version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: fda-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: fda 
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork  

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fda
    depends_on:
      - postgres
    ports:
      - "3000:3000" 
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: fda 
    volumes:
      - .:/app
    networks:
      - mynetwork  

volumes:
  postgres-data:

networks:
  mynetwork:  
    driver: bridge 